# Change these first
owner: Auroville # Your GitHub organization or username, where this repository lives
repo: checkbot # The name of this repository

sites:
  - name: Matrimandir Public Website
    url: https://matrimandir.org
  - name: Matrimandir Booking
    url: https://mmbooking.auroville.org.in
  - name: Talam Payment Pages
    url: https://pay.auroville.org
  - name: Proposal
    url: https://proposals.auroville.org.in
  - name: Campus Platform
    url: https://edu.auroville.org
  - name: Directory
    url: https://directory.auroville.org.in
  - name: Visitors Centre Online Booking
    url: https://visit.auroville.org 
  - name: House Transfer 
    url: https://housing.auroville.org.in 
  - name: Bazaar
    url: https://bazaar.auroville.org.in
  - name: Events Calendar
    url: https://events.auroville.org.in
  - name: Farm Management
    url: https://farms-dairy.auroville.org.in
  - name: Transport
    url: https://transport.auroville.org.in
  - name: Auroville Today
    url: https://avtoday.auroville.org  
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  cname: status.auroville.org # Custom domain CNAME
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Checkbot
  introTitle: "**Checkbot** continously monitors sites developed and maintained by Talam and Auroville Web Services."
  introMessage: The status of each of the sites can be seen below. If there is an incidence with one of these sites, our engineers are automatically notified and the status of the incident will be also be updated here as they work on to resolve it.
  navbar:
    - title: Status
      href: /
    - title: Issue Tracker
      href: https://github.com/$OWNER/$REPO/issues
  robotsText: "User-agent: * \n Disallow: /"

assignees:
  - Azhaganandhan

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
